import type {Metadata} from "next";
import {ReactNode} from "react";
import Script from "next/script";
import {Inter} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css'
import './styles/scss.scss'
import Navbar from "@/app/components/Navbar";
import StoreProvider from "@/app/StoreProvider";
import Footer from "@/app/components/Footer";
import ControlPanel from "@/app/components/ControlPanel";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Paint with next js",
    description: "Generated by create next app",
    icons: {
        icon: "/images/favicon-32x32.png",
    },
};

export default function RootLayout({children}: Readonly<{ children: ReactNode}>) {
    return (
        <html lang="en">
        <body className={`bg-dark  ${inter.className}`}>
        <div className="container-fluid dark_theme">
            <div className="row">
                <StoreProvider>
                    <Navbar/>
                    <ControlPanel/>
                    {children}
                    <Footer/>
                </StoreProvider>
            </div>
        </div>
        <Script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossOrigin="anonymous"
        />
        </body>
        </html>
    );
}
