import type {Metadata} from "next";
import Script from "next/script";
import {Inter} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import './styles/scss.scss'
import Navbar from "@/app/components/Navbar";
import ColorPanel from "@/app/components/ColorPanel";
import StoreProvider from "@/app/StoreProvider";
import Footer from "@/app/components/Footer";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Paint with next js",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`bg-dark ${inter.className}`}>
        <div className="container-fluid dark_theme">
            <div className="row">
                <StoreProvider>
                    <Navbar/>
                    <ColorPanel/>
                    {children}
                    <Footer/>
                </StoreProvider>
            </div>
        </div>
        <Script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossOrigin="anonymous"
        />
        </body>
        </html>
    );
}
